-- =============================================
-- Inventory Reconciliation System - Rollback Script
-- Description: Drops reconciliation tables and indexes
-- Author: System
-- Date: 2025-10-22
-- WARNING: This will delete all reconciliation data!
-- =============================================

USE asset_management;
GO

PRINT '==============================================';
PRINT 'Rolling Back Reconciliation Tables...';
PRINT 'WARNING: This will delete all reconciliation data!';
PRINT '==============================================';
PRINT '';

-- Drop indexes first
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_RECONCILIATION_RECORDS_RECONCILED_BY'
    AND object_id = OBJECT_ID('RECONCILIATION_RECORDS'))
BEGIN
    DROP INDEX IX_RECONCILIATION_RECORDS_RECONCILED_BY ON RECONCILIATION_RECORDS;
    PRINT 'Index IX_RECONCILIATION_RECORDS_RECONCILED_BY dropped.';
END

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_RECONCILIATION_RECORDS_STATUS'
    AND object_id = OBJECT_ID('RECONCILIATION_RECORDS'))
BEGIN
    DROP INDEX IX_RECONCILIATION_RECORDS_STATUS ON RECONCILIATION_RECORDS;
    PRINT 'Index IX_RECONCILIATION_RECORDS_STATUS dropped.';
END

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_RECONCILIATION_RECORDS_ASSET'
    AND object_id = OBJECT_ID('RECONCILIATION_RECORDS'))
BEGIN
    DROP INDEX IX_RECONCILIATION_RECORDS_ASSET ON RECONCILIATION_RECORDS;
    PRINT 'Index IX_RECONCILIATION_RECORDS_ASSET dropped.';
END

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_RECONCILIATION_RECORDS_PROCESS'
    AND object_id = OBJECT_ID('RECONCILIATION_RECORDS'))
BEGIN
    DROP INDEX IX_RECONCILIATION_RECORDS_PROCESS ON RECONCILIATION_RECORDS;
    PRINT 'Index IX_RECONCILIATION_RECORDS_PROCESS dropped.';
END

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_RECONCILIATION_CREATED_AT'
    AND object_id = OBJECT_ID('RECONCILIATION_PROCESSES'))
BEGIN
    DROP INDEX IX_RECONCILIATION_CREATED_AT ON RECONCILIATION_PROCESSES;
    PRINT 'Index IX_RECONCILIATION_CREATED_AT dropped.';
END

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_RECONCILIATION_CREATED_BY'
    AND object_id = OBJECT_ID('RECONCILIATION_PROCESSES'))
BEGIN
    DROP INDEX IX_RECONCILIATION_CREATED_BY ON RECONCILIATION_PROCESSES;
    PRINT 'Index IX_RECONCILIATION_CREATED_BY dropped.';
END

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_RECONCILIATION_STATUS'
    AND object_id = OBJECT_ID('RECONCILIATION_PROCESSES'))
BEGIN
    DROP INDEX IX_RECONCILIATION_STATUS ON RECONCILIATION_PROCESSES;
    PRINT 'Index IX_RECONCILIATION_STATUS dropped.';
END
GO

-- Drop tables (child table first due to foreign key constraints)
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RECONCILIATION_RECORDS')
BEGIN
    DROP TABLE RECONCILIATION_RECORDS;
    PRINT 'Table RECONCILIATION_RECORDS dropped successfully.';
END
ELSE
BEGIN
    PRINT 'Table RECONCILIATION_RECORDS does not exist.';
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RECONCILIATION_PROCESSES')
BEGIN
    DROP TABLE RECONCILIATION_PROCESSES;
    PRINT 'Table RECONCILIATION_PROCESSES dropped successfully.';
END
ELSE
BEGIN
    PRINT 'Table RECONCILIATION_PROCESSES does not exist.';
END
GO

-- Verify cleanup
PRINT '';
PRINT '==============================================';
PRINT 'Rollback Complete!';
PRINT '==============================================';
PRINT '';
PRINT 'Verifying table removal...';

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RECONCILIATION_PROCESSES')
    AND NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RECONCILIATION_RECORDS')
BEGIN
    PRINT 'SUCCESS: All reconciliation tables have been removed.';
END
ELSE
BEGIN
    PRINT 'WARNING: Some tables may still exist. Please check manually.';
END

GO
