-- ============================================================================
-- Script: Rollback RECONCILIATION_DISCREPANCIES Table
-- Description: Safely removes discrepancy tracking table and related changes
-- Author: Claude Code
-- Date: 2025-10-23
-- WARNING: This will delete all discrepancy data!
-- ============================================================================

USE asset_management;
GO

PRINT 'Starting rollback of RECONCILIATION_DISCREPANCIES table...';
GO

-- Drop indexes from RECONCILIATION_DISCREPANCIES
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DISCREPANCY_RECORD')
    DROP INDEX IX_DISCREPANCY_RECORD ON RECONCILIATION_DISCREPANCIES;

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DISCREPANCY_TYPE')
    DROP INDEX IX_DISCREPANCY_TYPE ON RECONCILIATION_DISCREPANCIES;

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DISCREPANCY_SEVERITY')
    DROP INDEX IX_DISCREPANCY_SEVERITY ON RECONCILIATION_DISCREPANCIES;

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DISCREPANCY_RESOLVED')
    DROP INDEX IX_DISCREPANCY_RESOLVED ON RECONCILIATION_DISCREPANCIES;

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DISCREPANCY_FIELD')
    DROP INDEX IX_DISCREPANCY_FIELD ON RECONCILIATION_DISCREPANCIES;

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DISCREPANCY_DETECTED_BY')
    DROP INDEX IX_DISCREPANCY_DETECTED_BY ON RECONCILIATION_DISCREPANCIES;

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DISCREPANCY_DETECTED_AT')
    DROP INDEX IX_DISCREPANCY_DETECTED_AT ON RECONCILIATION_DISCREPANCIES;

PRINT 'Indexes dropped from RECONCILIATION_DISCREPANCIES';
GO

-- Drop RECONCILIATION_DISCREPANCIES table
IF OBJECT_ID('RECONCILIATION_DISCREPANCIES', 'U') IS NOT NULL
BEGIN
    DROP TABLE RECONCILIATION_DISCREPANCIES;
    PRINT 'RECONCILIATION_DISCREPANCIES table dropped';
END
ELSE
BEGIN
    PRINT 'RECONCILIATION_DISCREPANCIES table does not exist';
END
GO

-- Drop has_discrepancies column and index from RECONCILIATION_RECORDS
IF EXISTS (
    SELECT * FROM sys.columns
    WHERE object_id = OBJECT_ID('RECONCILIATION_RECORDS')
    AND name = 'has_discrepancies'
)
BEGIN
    -- Drop index first
    IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_RECONCILIATION_HAS_DISCREPANCIES')
        DROP INDEX IX_RECONCILIATION_HAS_DISCREPANCIES ON RECONCILIATION_RECORDS;

    -- Drop column
    ALTER TABLE RECONCILIATION_RECORDS
    DROP COLUMN has_discrepancies;

    PRINT 'has_discrepancies column and index removed from RECONCILIATION_RECORDS';
END
ELSE
BEGIN
    PRINT 'has_discrepancies column does not exist in RECONCILIATION_RECORDS';
END
GO

PRINT 'Rollback completed successfully';
GO
